import {
  GET_USER_BY_ID,
  GET_USER_BY_TOKEN,
  GET_LEADERBOARD,
  GET_USERS,
} from "./userQuery";
import {
  FIND_ARTICLES,
  FIND_ARTICLE_BY_ID,
  FIND_ARTICLE_BY_MOST_DISLIKED,
  FIND_ARTICLES_BY_USER,
} from "./articleQuery";
import {
  FIND_DISLIKES_BY_USER_ID_FOR_ARTICLES,
  FIND_DISLIKES_BY_USER_ID_FOR_COMMENTS,
} from "./dislikeQuery";
import { GET_COMMENTS } from "./commentQuery";

export {
  GET_USER_BY_TOKEN,
  GET_USER_BY_ID,
  GET_LEADERBOARD,
  GET_USERS,
  FIND_ARTICLES,
  FIND_ARTICLE_BY_ID,
  FIND_ARTICLE_BY_MOST_DISLIKED,
  FIND_ARTICLES_BY_USER,
  FIND_DISLIKES_BY_USER_ID_FOR_ARTICLES,
  FIND_DISLIKES_BY_USER_ID_FOR_COMMENTS,
  GET_COMMENTS,
};
